### PR TITLE
added some information to work on debian 9 as well

### PR DESCRIPTION
**Pull request by sirtoobii**
Thank you for this awesome guide :+1:

### CODE REVIEW

**Comment by leviwheatcroft** [comment]
#1 has a full debian guide in debian.md. I think the plan was to rename readme.md to ubuntu.md or something and create a readme.md file referencing the two.

Did you want to take a look at debian.md in #1 and see how it differs from yours ? You can submit a PR against that fork, or get @TheReal1604 to merge #1 and then PR against master.

**Comment by TheReal1604** [comment]
@leviwheatcroft @sirtoobii  I take a look and merge appropriate. Thanks for your contributions!

**Comment by TheReal1604** [comment]
@sirtoobii Is there something missing in https://github.com/TheReal1604/disk-encryption-hetzner/blob/master/debian.md ? Or should we create a separate Guide for the hardware raid controller setup without LVM? What you think?

**Comment by sirtoobii** [comment]
I think it would be better to create a seperate guide. I'm also not sure if the hardware-raid-guide works "standalone", because in my oppinion the part about configuring the ssh-key for dropbear is missing or at least not very clear.

**Comment by TheReal1604** [comment]
@sirtoobii thanks for your contributions! I take a look into this in the next weeks.

**Pull request merged**
