### PR TITLE
Fixed some bugs and updated a missing but important command

### PR DESCRIPTION
**Pull request by martinseener**

### CODE REVIEW

**Comment by TheReal1604** [comment]
Awesome, thank you!

**Comment by martinseener** [comment]
Just wanted to mention that i also used your tutorials (or parts of it) to setup my own server and write a blog post about that. I also acknowledged your work here in the post down below. So Thank you for your work and feel free to use my post if you need it. Here it is: https://www.sysorchestra.com/2018/06/14/hetzner-root-server-with-dual-hardware-raid-1-and-lvm-on-luks-on-debian-9/

**Comment by martinseener** [comment]
@TheReal1604 if you like, i can also contribute my posts commands in shorter form as a markdown tutorial for your repo here. Just answer to this comment ;)

**Comment by TheReal1604** [comment]
Thanks for referencing this repo at you blog post, this is really cool!

I would really appreciate it, if you can open another PR with a short form of the commands from your blog post, so we have another tested tutorial with hardware raid and a hetzner machine. 👍 

@martinseener awesome :)

**Pull request merged**
